language: node_js
node_js:
- 4.2.4
addons:
  firefox: '43.0'
env:
  global:
  - secure: reHCrpMsX3kkW7IyNRdnMcdNsMd7WhJ/QhYa/CBTwUGeAjSRIJyWGnhZym3C+4QStam9mMDBMFFySQoItmT58od6258WVNoYAh5UntTQlxsfwRvDPhu6rqjL7jTFA2PwzUOnIUK+drgavNUerHtWXpJLJxhTq8Sgr89IaLhO5ad/tR9ee+Zq7FwYgwXvD6SATNs6jiC89aF671Lqsh7rNhi9hBCbglaqeNVa82QgooueIuQxVx8xLnVeN5Stu7KRjaoMjsEMuQFRbYgKq1SCiGMCT2SOpgYM3WRxsCjiV/+cPXWAIWbda7hmbPTho6VnaTZEpez26FPx3uqEhE7nhFwkVogDmRb++ODagf+GPUVQyPozCIinmuYxMWt1OXOBK2QVCGh75iZtqOnEDynDONHWyivYpgZHp3aj03XQmRPAqdUU9tGbyZUbCY3FEtDVlfg6VH2Y6vMdhlW341qXFC+gRn/7kcBJr6fVzXhtFKXy9qbBg78XjRzrpGJGGaUPqVLSrDBCg++Z3Q13Wb2OdX1wIZ/An+/gSTgOu2vqy46lBJCE7jJXEGQhujXGPEFqbmV458OpBjcfmEbwqR5rl0L3b4CfdvitcI3Hmo+nJ64hOEzF90rkT2Tc8+S+PjRYD5xRnZD1FZm03sd0Dczi6LXjGlWD1mNmSWwwSzIZSNI=
before_install:
- npm install -g jspm
- jspm config endpoints.github.auth $JSPM_GITHUB_AUTH_TOKEN
- pip install --user codecov
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm install
script:
- npm run buildprod
- npm run citest
after_success:
- codecov
