language: node_js
node_js:
  - "4.2.4"

addons:
  firefox: "43.0"

before_install:
  - pip install --user codecov

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install
#  - npm start > /dev/null &
#  - npm run selenium > /dev/null &
#  - sleep 10 # give server time to start

script:
  - npm run buildprod
  - npm run citest
#  - npm run e2e

after_success:
  - codecov